version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mywarehouse_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/sites-available/default
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "8000:80"
    networks:
      - mywarehouse_network
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: mywarehouse_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mywarehouse
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: mywarehouse
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mywarehouse_network

  redis:
    image: redis:alpine
    container_name: mywarehouse_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mywarehouse_network

networks:
  mywarehouse_network:
    driver: bridge

volumes:
  dbdata: 